# Generated by Django 5.2 on 2025-05-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Marca',
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'carros'},
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand'),
        ),
    ]
