# Generated by Django 5.2 on 2025-05-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brand_alter_car_options_alter_car_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'carro'},
        ),
    ]
