# Generated by Django 5.2 on 2025-05-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand',
            new_name='brand_name',
        ),
    ]
