# Generated by Django 5.2 on 2025-05-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_rename_brand_brand_brand_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_name',
            new_name='brand',
        ),
    ]
