# Generated by Django 5.2 on 2025-05-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_rename_brand_name_brand_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand',
            new_name='name',
        ),
    ]
